# Generated by Django 3.1.13 on 2024-12-18 08:18

from django.db import migrations, models
import django.db.models.deletion
import django_lexorank.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', django_lexorank.fields.RankField(db_index=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', django_lexorank.fields.RankField(db_index=True, editable=False, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.board')),
            ],
            options={
                'ordering': ['rank'],
                'abstract': False,
            },
        ),
    ]
